name       : libmusicbrainz
version    : 5.1.0
release    : 2
source     :
    - https://github.com/metabrainz/libmusicbrainz/archive/release-5.1.0.tar.gz : 6e1dc7158d884748287eb14159c4e2866eb4f4e5559765c7c17621c4a3c802c8
license    : LGPL-2.1
component  : multimedia.library
summary    : MusicBrainz Client Library
description: |
    A library for accessing MusicBrainz servers
builddeps  :
    - pkgconfig(neon)
setup      : |
    %cmake -DLIB_SUFFIX=64 .
build      : |
    %make
install    : |
    %make_install
